// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz4OQxizGtMidLSTeonlSD6SE7P-l38KQ',
    appId: '1:339953698791:web:690be073749c1d27af1f42',
    messagingSenderId: '339953698791',
    projectId: 'rcet-complaint',
    authDomain: 'rcet-complaint.firebaseapp.com',
    storageBucket: 'rcet-complaint.firebasestorage.app',
    measurementId: 'G-KG8XWVEBJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-XK0NAG6POXtJVOA--tKzKxPebz2bPTw',
    appId: '1:339953698791:android:30900dc42dc46147af1f42',
    messagingSenderId: '339953698791',
    projectId: 'rcet-complaint',
    storageBucket: 'rcet-complaint.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5ijyon4CBVUzIbQEirjJyu_0L5THsB9A',
    appId: '1:339953698791:ios:ba030d59cb52cc49af1f42',
    messagingSenderId: '339953698791',
    projectId: 'rcet-complaint',
    storageBucket: 'rcet-complaint.firebasestorage.app',
    iosBundleId: 'com.example.rcetComplaint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5ijyon4CBVUzIbQEirjJyu_0L5THsB9A',
    appId: '1:339953698791:ios:ba030d59cb52cc49af1f42',
    messagingSenderId: '339953698791',
    projectId: 'rcet-complaint',
    storageBucket: 'rcet-complaint.firebasestorage.app',
    iosBundleId: 'com.example.rcetComplaint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz4OQxizGtMidLSTeonlSD6SE7P-l38KQ',
    appId: '1:339953698791:web:e160533ce2c081f1af1f42',
    messagingSenderId: '339953698791',
    projectId: 'rcet-complaint',
    authDomain: 'rcet-complaint.firebaseapp.com',
    storageBucket: 'rcet-complaint.firebasestorage.app',
    measurementId: 'G-KMJ8HCHS4D',
  );
}
